# Generated by Django 4.1.3 on 2022-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('story', models.TextField(max_length=450)),
                ('cover', models.TextField(default='null', max_length=150)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
