# Generated by Django 4.1.3 on 2022-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_storytitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytitle',
            name='cover',
            field=models.TextField(default='null', max_length=150),
        ),
    ]
